DROP TABLE IF EXISTS Interests;
DROP TABLE IF EXISTS Animals;
DROP TABLE IF EXISTS Species;


CREATE TABLE Species(
    Id INT PRIMARY KEY IDENTITY,
    Species VARCHAR(50) NOT NULL UNIQUE,
    FriendlyName VARCHAR(50) NOT NULL
)

CREATE TABLE Animals(
    Id INT PRIMARY KEY IDENTITY,
    Name VARCHAR(50) not NULL,
    SpeciesID INT NOT NULL REFERENCES Species(Id),
    ContactEmail VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Interests(
    AnimalID INT NOT NULL, 
    SpeciesID INT NOT NULL,
    PRIMARY KEY (AnimalID,speciesID)
)